CREATE DATABASE AMAZON;

GO

USE AMAZON;

CREATE TABLE CATEGORIES (
	CategoryID INT IDENTITY(1,1) PRIMARY KEY,
	Name VARCHAR(150) NOT NULL,
	Description VARCHAR(500)
);

CREATE TABLE CUSTOMERS (
	CustomerID INT IDENTITY(1,1) PRIMARY KEY,
	FirstName VARCHAR(50) NOT NULL,
	LastName VARCHAR(50) NOT NULL,
	Email VARCHAR(150) NOT NULL,
	PhoneNumber VARCHAR(15) NOT NULL,
	ShippingAddress VARCHAR(100) NOT NULL
);

CREATE TABLE SELLERS (
	SellerID INT IDENTITY(1,1) PRIMARY KEY,
	Name VARCHAR(150) NOT NULL,
	Email VARCHAR(100) NOT NULL,
	Region VARCHAR(40) NOT NULL,
	PhoneNumber VARCHAR(15) NOT NULL,
	ProductsRating DECIMAL(4,2)
);

CREATE TABLE PRODUCTS (
	ProductID INT IDENTITY(1,1) PRIMARY KEY,
	Name VARCHAR(150) NOT NULL,
	Brand VARCHAR(100) NOT NULL,
	Description VARCHAR(500) NOT NULL,
	Price DECIMAL(7,2) NOT NULL,
	Quantity INT NOT NULL,
	SellerID INT NOT NULL,
	CategoryID INT NOT NULL,
	FOREIGN KEY (SellerID) REFERENCES SELLERS(SellerID),
	FOREIGN KEY (CategoryID) REFERENCES CATEGORIES(CategoryID)
);

CREATE TABLE REVIEWS (
	ReviewID INT IDENTITY(1,1) PRIMARY KEY,
	Rating DECIMAL(4,2),
	Comment VARCHAR(500),
	CustomerID INT NOT NULL,
	ProductID INT NOT NULL,
	FOREIGN KEY (CustomerID) REFERENCES CUSTOMERS(CustomerID),
	FOREIGN KEY (ProductID) REFERENCES PRODUCTS(ProductID)
);

CREATE TABLE ORDERS (
	OrderID INT IDENTITY(1,1) PRIMARY KEY,
	Status VARCHAR(20) NOT NULL,
	OrderDate DATE NOT NULL,
	TotalAmount DECIMAL(8, 2),
	CustomerID INT NOT NULL,
	FOREIGN KEY (CustomerID) REFERENCES CUSTOMERS(CustomerID)
);

CREATE TABLE PAYMENT(
	PaymentID INT IDENTITY(1,1) PRIMARY KEY,
	PaymentStatus VARCHAR(20) NOT NULL,
	PaymentMethod VARCHAR(40) NOT NULL,
	OrderID INT NOT NULL,
	FOREIGN KEY (OrderID) REFERENCES ORDERS(OrderID)
);

CREATE TABLE ORDER_PRODUCTS (
	OrderID INT NOT NULL,
	ProductID INT NOT NULL,
	Quantity INT NOT NULL,
	PRIMARY KEY (OrderID, ProductID),
	FOREIGN KEY (OrderID) REFERENCES ORDERS(OrderID),
	FOREIGN KEY (ProductID) REFERENCES PRODUCTS(ProductID)
);